
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.infomovil.webapp.clientWsInfomovil;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-09-01T13:32:51.822-05:00
 * Generated source version: 2.7.17
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsInfomovilDomainService",
                      portName = "WsInfomovilDomainPort",
                      targetNamespace = "http://ws.webservice.infomovil.org/",
                      wsdlLocation = "/var/folders/17/mcmbc2y126n3tjfj48kp4kfh0000gp/T/tempdir4672397050342039818.tmp/wsInfomovildomain_1.wsdl",
                      endpointInterface = "com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain")
                      
public class WsInfomovilDomainImpl implements WsInfomovilDomain {

    private static final Logger LOG = Logger.getLogger(WsInfomovilDomainImpl.class.getName());

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateDomain(com.infomovil.webapp.clientWsInfomovil.UpdateDomain  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateDomainResponse updateDomain(UpdateDomain parameters) { 
        LOG.info("Executing operation updateDomain");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateDomainResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#deleteOfferRecord(com.infomovil.webapp.clientWsInfomovil.DeleteOfferRecord  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DeleteOfferRecordResponse deleteOfferRecord(DeleteOfferRecord parameters) { 
        LOG.info("Executing operation deleteOfferRecord");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.DeleteOfferRecordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioGuardarVideo(com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarVideo  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarVideoResponse crearSitioGuardarVideo(CrearSitioGuardarVideo parameters) { 
        LOG.info("Executing operation crearSitioGuardarVideo");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarVideoResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertUserDomain1(com.infomovil.webapp.clientWsInfomovil.InsertUserDomain1  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertUserDomain1Response insertUserDomain1(InsertUserDomain1 parameters) { 
        LOG.info("Executing operation insertUserDomain1");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertUserDomain1Response _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#sessionActiva(com.infomovil.webapp.clientWsInfomovil.SessionActiva  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.SessionActivaResponse sessionActiva(SessionActiva parameters) { 
        LOG.info("Executing operation sessionActiva");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.SessionActivaResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#deleteLocRecord(com.infomovil.webapp.clientWsInfomovil.DeleteLocRecord  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DeleteLocRecordResponse deleteLocRecord(DeleteLocRecord parameters) { 
        LOG.info("Executing operation deleteLocRecord");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.DeleteLocRecordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertKeywordDataAddress(com.infomovil.webapp.clientWsInfomovil.InsertKeywordDataAddress  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertKeywordDataAddressResponse insertKeywordDataAddress(InsertKeywordDataAddress parameters) { 
        LOG.info("Executing operation insertKeywordDataAddress");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertKeywordDataAddressResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertVideo(com.infomovil.webapp.clientWsInfomovil.InsertVideo  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertVideoResponse insertVideo(InsertVideo parameters) { 
        LOG.info("Executing operation insertVideo");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertVideoResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getItemsGratisDomain(com.infomovil.webapp.clientWsInfomovil.GetItemsGratisDomain  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GetItemsGratisDomainResponse getItemsGratisDomain(GetItemsGratisDomain parameters) { 
        LOG.info("Executing operation getItemsGratisDomain");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GetItemsGratisDomainResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioGetWebHash(com.infomovil.webapp.clientWsInfomovil.CrearSitioGetWebHash  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioGetWebHashResponse crearSitioGetWebHash(CrearSitioGetWebHash parameters) { 
        LOG.info("Executing operation crearSitioGetWebHash");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioGetWebHashResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertRecordNaptr(com.infomovil.webapp.clientWsInfomovil.InsertRecordNaptr  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertRecordNaptrResponse insertRecordNaptr(InsertRecordNaptr parameters) { 
        LOG.info("Executing operation insertRecordNaptr");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertRecordNaptrResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertImage(com.infomovil.webapp.clientWsInfomovil.InsertImage  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertImageResponse insertImage(InsertImage parameters) { 
        LOG.info("Executing operation insertImage");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertImageResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getDomain(java.lang.String  email ,)java.lang.String  password ,)java.lang.String  tipoDispositivo ,)java.lang.String  sistema ,)java.lang.String  notificacion ,)java.lang.String  redSocial ,)java.lang.String  suscrito ,)java.lang.String  tipoPlan ,)java.lang.String  medioPago ,)java.lang.String  versionSistema )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DominioVO getDomain(java.lang.String email,java.lang.String password,java.lang.String tipoDispositivo,java.lang.String sistema,java.lang.String notificacion,java.lang.String redSocial,java.lang.String suscrito,java.lang.String tipoPlan,java.lang.String medioPago,java.lang.String versionSistema) { 
        LOG.info("Executing operation getDomain");
        System.out.println(email);
        System.out.println(password);
        System.out.println(tipoDispositivo);
        System.out.println(sistema);
        System.out.println(notificacion);
        System.out.println(redSocial);
        System.out.println(suscrito);
        System.out.println(tipoPlan);
        System.out.println(medioPago);
        System.out.println(versionSistema);
        try {
            com.infomovil.webapp.clientWsInfomovil.DominioVO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioPublicar(com.infomovil.webapp.clientWsInfomovil.CrearSitioPublicar  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioPublicarResponse crearSitioPublicar(CrearSitioPublicar parameters) { 
        LOG.info("Executing operation crearSitioPublicar");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioPublicarResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateinsertOfferRecord(com.infomovil.webapp.clientWsInfomovil.UpdateinsertOfferRecord  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateinsertOfferRecordResponse updateinsertOfferRecord(UpdateinsertOfferRecord parameters) { 
        LOG.info("Executing operation updateinsertOfferRecord");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateinsertOfferRecordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getExistUser(com.infomovil.webapp.clientWsInfomovil.GetExistUser  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GetExistUserResponse getExistUser(GetExistUser parameters) { 
        LOG.info("Executing operation getExistUser");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GetExistUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertKeyWordData(com.infomovil.webapp.clientWsInfomovil.InsertKeyWordData  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertKeyWordDataResponse insertKeyWordData(InsertKeyWordData parameters) { 
        LOG.info("Executing operation insertKeyWordData");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertKeyWordDataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateInserLocRecord(com.infomovil.webapp.clientWsInfomovil.UpdateInserLocRecord  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateInserLocRecordResponse updateInserLocRecord(UpdateInserLocRecord parameters) { 
        LOG.info("Executing operation updateInserLocRecord");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateInserLocRecordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#generaHashMovilizaSitio(com.infomovil.webapp.clientWsInfomovil.GeneraHashMovilizaSitio  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GeneraHashMovilizaSitioResponse generaHashMovilizaSitio(GeneraHashMovilizaSitio parameters) { 
        LOG.info("Executing operation generaHashMovilizaSitio");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GeneraHashMovilizaSitioResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioGuardar(com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardar  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarResponse crearSitioGuardar(CrearSitioGuardar parameters) { 
        LOG.info("Executing operation crearSitioGuardar");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#cambioPassword(com.infomovil.webapp.clientWsInfomovil.CambioPassword  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CambioPasswordResponse cambioPassword(CambioPassword parameters) { 
        LOG.info("Executing operation cambioPassword");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CambioPasswordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateImage(java.lang.String  domainId ,)java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO>  arg1 ,)java.lang.String  token ,)java.lang.String  sistema ,)java.lang.String  versionSistema )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DominioVO updateImage(java.lang.String domainId,java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO> arg1,java.lang.String token,java.lang.String sistema,java.lang.String versionSistema) { 
        LOG.info("Executing operation updateImage");
        System.out.println(domainId);
        System.out.println(arg1);
        System.out.println(token);
        System.out.println(sistema);
        System.out.println(versionSistema);
        try {
            com.infomovil.webapp.clientWsInfomovil.DominioVO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateRecordNaptr(java.lang.String  domainId ,)java.util.List<com.infomovil.webapp.clientWsInfomovil.RecordNaptrVO>  recordNaptrVO ,)java.lang.String  token )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DominioVO updateRecordNaptr(java.lang.String domainId,java.util.List<com.infomovil.webapp.clientWsInfomovil.RecordNaptrVO> recordNaptrVO,java.lang.String token) { 
        LOG.info("Executing operation updateRecordNaptr");
        System.out.println(domainId);
        System.out.println(recordNaptrVO);
        System.out.println(token);
        try {
            com.infomovil.webapp.clientWsInfomovil.DominioVO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getExistDomain(com.infomovil.webapp.clientWsInfomovil.GetExistDomain  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GetExistDomainResponse getExistDomain(GetExistDomain parameters) { 
        LOG.info("Executing operation getExistDomain");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GetExistDomainResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#deleteImage(com.infomovil.webapp.clientWsInfomovil.DeleteImage  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DeleteImageResponse deleteImage(DeleteImage parameters) { 
        LOG.info("Executing operation deleteImage");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.DeleteImageResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioResetPassword(com.infomovil.webapp.clientWsInfomovil.CrearSitioResetPassword  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioResetPasswordResponse crearSitioResetPassword(CrearSitioResetPassword parameters) { 
        LOG.info("Executing operation crearSitioResetPassword");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioResetPasswordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioRegistrar(com.infomovil.webapp.clientWsInfomovil.CrearSitioRegistrar  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioRegistrarResponse crearSitioRegistrar(CrearSitioRegistrar parameters) { 
        LOG.info("Executing operation crearSitioRegistrar");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioRegistrarResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#deleteRecordNaptr(com.infomovil.webapp.clientWsInfomovil.DeleteRecordNaptr  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DeleteRecordNaptrResponse deleteRecordNaptr(DeleteRecordNaptr parameters) { 
        LOG.info("Executing operation deleteRecordNaptr");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.DeleteRecordNaptrResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioLogin(com.infomovil.webapp.clientWsInfomovil.CrearSitioLogin  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioLoginResponse crearSitioLogin(CrearSitioLogin parameters) { 
        LOG.info("Executing operation crearSitioLogin");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioLoginResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#statusDominio(com.infomovil.webapp.clientWsInfomovil.StatusDominio  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.StatusDominioResponse statusDominio(StatusDominio parameters) { 
        LOG.info("Executing operation statusDominio");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.StatusDominioResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateColor(com.infomovil.webapp.clientWsInfomovil.UpdateColor  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateColorResponse updateColor(UpdateColor parameters) { 
        LOG.info("Executing operation updateColor");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateColorResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#deleteVideo(com.infomovil.webapp.clientWsInfomovil.DeleteVideo  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DeleteVideoResponse deleteVideo(DeleteVideo parameters) { 
        LOG.info("Executing operation deleteVideo");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.DeleteVideoResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioGuardarUbicacion(com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarUbicacion  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarUbicacionResponse crearSitioGuardarUbicacion(CrearSitioGuardarUbicacion parameters) { 
        LOG.info("Executing operation crearSitioGuardarUbicacion");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarUbicacionResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#compraDominio(com.infomovil.webapp.clientWsInfomovil.CompraDominio  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CompraDominioResponse compraDominio(CompraDominio parameters) { 
        LOG.info("Executing operation compraDominio");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CompraDominioResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getNumVisitas(com.infomovil.webapp.clientWsInfomovil.GetNumVisitas  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GetNumVisitasResponse getNumVisitas(GetNumVisitas parameters) { 
        LOG.info("Executing operation getNumVisitas");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GetNumVisitasResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertUpdateInfoUser(com.infomovil.webapp.clientWsInfomovil.InsertUpdateInfoUser  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertUpdateInfoUserResponse insertUpdateInfoUser(InsertUpdateInfoUser parameters) { 
        LOG.info("Executing operation insertUpdateInfoUser");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertUpdateInfoUserResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#deleteKeyWordData(com.infomovil.webapp.clientWsInfomovil.DeleteKeyWordData  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DeleteKeyWordDataResponse deleteKeyWordData(DeleteKeyWordData parameters) { 
        LOG.info("Executing operation deleteKeyWordData");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.DeleteKeyWordDataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateKeyWordData(com.infomovil.webapp.clientWsInfomovil.UpdateKeyWordData  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateKeyWordDataResponse updateKeyWordData(UpdateKeyWordData parameters) { 
        LOG.info("Executing operation updateKeyWordData");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateKeyWordDataResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getEstadisticas(com.infomovil.webapp.clientWsInfomovil.GetEstadisticas  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GetEstadisticasResponse getEstadisticas(GetEstadisticas parameters) { 
        LOG.info("Executing operation getEstadisticas");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GetEstadisticasResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateTemplate(com.infomovil.webapp.clientWsInfomovil.UpdateTemplate  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateTemplateResponse updateTemplate(UpdateTemplate parameters) { 
        LOG.info("Executing operation updateTemplate");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateTemplateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioDeleteImage(com.infomovil.webapp.clientWsInfomovil.CrearSitioDeleteImage  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioDeleteImageResponse crearSitioDeleteImage(CrearSitioDeleteImage parameters) { 
        LOG.info("Executing operation crearSitioDeleteImage");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioDeleteImageResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#cerrarSession(com.infomovil.webapp.clientWsInfomovil.CerrarSession  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CerrarSessionResponse cerrarSession(CerrarSession parameters) { 
        LOG.info("Executing operation cerrarSession");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CerrarSessionResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearImagenes(*
     */
    public int crearImagenes() { 
        LOG.info("Executing operation crearImagenes");
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#cancelarCuenta(com.infomovil.webapp.clientWsInfomovil.CancelarCuenta  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CancelarCuentaResponse cancelarCuenta(CancelarCuenta parameters) { 
        LOG.info("Executing operation cancelarCuenta");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CancelarCuentaResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateTextRecord(com.infomovil.webapp.clientWsInfomovil.UpdateTextRecord  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateTextRecordResponse updateTextRecord(UpdateTextRecord parameters) { 
        LOG.info("Executing operation updateTextRecord");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateTextRecordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioInsertImage(com.infomovil.webapp.clientWsInfomovil.CrearSitioInsertImage  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioInsertImageResponse crearSitioInsertImage(CrearSitioInsertImage parameters) { 
        LOG.info("Executing operation crearSitioInsertImage");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioInsertImageResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getExistCampaniaByMail(com.infomovil.webapp.clientWsInfomovil.GetExistCampaniaByMail  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GetExistCampaniaByMailResponse getExistCampaniaByMail(GetExistCampaniaByMail parameters) { 
        LOG.info("Executing operation getExistCampaniaByMail");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GetExistCampaniaByMailResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getDomainLogin(java.lang.String  email ,)java.lang.String  password ,)java.lang.String  tipoDispositivo ,)java.lang.String  sistema ,)java.lang.String  notificacion ,)java.lang.String  redSocial ,)java.lang.String  suscrito ,)java.lang.String  tipoPlan ,)java.lang.String  medioPago ,)java.lang.String  versionSistema )*
     */
    public com.infomovil.webapp.clientWsInfomovil.DominioVO getDomainLogin(java.lang.String email,java.lang.String password,java.lang.String tipoDispositivo,java.lang.String sistema,java.lang.String notificacion,java.lang.String redSocial,java.lang.String suscrito,java.lang.String tipoPlan,java.lang.String medioPago,java.lang.String versionSistema) { 
        LOG.info("Executing operation getDomainLogin");
        System.out.println(email);
        System.out.println(password);
        System.out.println(tipoDispositivo);
        System.out.println(sistema);
        System.out.println(notificacion);
        System.out.println(redSocial);
        System.out.println(suscrito);
        System.out.println(tipoPlan);
        System.out.println(medioPago);
        System.out.println(versionSistema);
        try {
            com.infomovil.webapp.clientWsInfomovil.DominioVO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getImagenes(java.lang.String  email ,)java.lang.Integer  domainId ,)java.lang.String  sistema ,)java.lang.String  versionSistema )*
     */
    public java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO> getImagenes(java.lang.String email,java.lang.Integer domainId,java.lang.String sistema,java.lang.String versionSistema) { 
        LOG.info("Executing operation getImagenes");
        System.out.println(email);
        System.out.println(domainId);
        System.out.println(sistema);
        System.out.println(versionSistema);
        try {
            java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#cambiaNombreRecurso(com.infomovil.webapp.clientWsInfomovil.CambiaNombreRecurso  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CambiaNombreRecursoResponse cambiaNombreRecurso(CambiaNombreRecurso parameters) { 
        LOG.info("Executing operation cambiaNombreRecurso");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CambiaNombreRecursoResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioExisteDominio(com.infomovil.webapp.clientWsInfomovil.CrearSitioExisteDominio  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioExisteDominioResponse crearSitioExisteDominio(CrearSitioExisteDominio parameters) { 
        LOG.info("Executing operation crearSitioExisteDominio");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioExisteDominioResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#insertUserCam(com.infomovil.webapp.clientWsInfomovil.InsertUserCam  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.InsertUserCamResponse insertUserCam(InsertUserCam parameters) { 
        LOG.info("Executing operation insertUserCam");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.InsertUserCamResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#updateDesCorta(com.infomovil.webapp.clientWsInfomovil.UpdateDesCorta  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.UpdateDesCortaResponse updateDesCorta(UpdateDesCorta parameters) { 
        LOG.info("Executing operation updateDesCorta");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.UpdateDesCortaResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#catalogoDominios(*
     */
    public java.util.List<com.infomovil.webapp.clientWsInfomovil.Catalogo> catalogoDominios() { 
        LOG.info("Executing operation catalogoDominios");
        try {
            java.util.List<com.infomovil.webapp.clientWsInfomovil.Catalogo> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#createDomain(com.infomovil.webapp.clientWsInfomovil.CreateDomain  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CreateDomainResponse createDomain(CreateDomain parameters) { 
        LOG.info("Executing operation createDomain");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CreateDomainResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#getFechaExpiracion(com.infomovil.webapp.clientWsInfomovil.GetFechaExpiracion  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GetFechaExpiracionResponse getFechaExpiracion(GetFechaExpiracion parameters) { 
        LOG.info("Executing operation getFechaExpiracion");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GetFechaExpiracionResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#generaHashCambioPassword(com.infomovil.webapp.clientWsInfomovil.GeneraHashCambioPassword  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.GeneraHashCambioPasswordResponse generaHashCambioPassword(GeneraHashCambioPassword parameters) { 
        LOG.info("Executing operation generaHashCambioPassword");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.GeneraHashCambioPasswordResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.infomovil.webapp.clientWsInfomovil.WsInfomovilDomain#crearSitioCargar(com.infomovil.webapp.clientWsInfomovil.CrearSitioCargar  parameters )*
     */
    public com.infomovil.webapp.clientWsInfomovil.CrearSitioCargarResponse crearSitioCargar(CrearSitioCargar parameters) { 
        LOG.info("Executing operation crearSitioCargar");
        System.out.println(parameters);
        try {
            com.infomovil.webapp.clientWsInfomovil.CrearSitioCargarResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
