
package com.infomovil.webapp.clientWsInfomovil;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.17
 * 2015-09-03T13:50:32.372-05:00
 * Generated source version: 2.7.17
 * 
 */
public final class WsInfomovilDomain_WsInfomovilDomainPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.webservice.infomovil.org/", "WsInfomovilDomainService");

    private WsInfomovilDomain_WsInfomovilDomainPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsInfomovilDomainService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsInfomovilDomainService ss = new WsInfomovilDomainService(wsdlURL, SERVICE_NAME);
        WsInfomovilDomain port = ss.getWsInfomovilDomainPort();  
        
        {
        System.out.println("Invoking updateDomain...");
        com.infomovil.webapp.clientWsInfomovil.UpdateDomain _updateDomain_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateDomainResponse _updateDomain__return = port.updateDomain(_updateDomain_parameters);
        System.out.println("updateDomain.result=" + _updateDomain__return);


        }
        {
        System.out.println("Invoking deleteOfferRecord...");
        com.infomovil.webapp.clientWsInfomovil.DeleteOfferRecord _deleteOfferRecord_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.DeleteOfferRecordResponse _deleteOfferRecord__return = port.deleteOfferRecord(_deleteOfferRecord_parameters);
        System.out.println("deleteOfferRecord.result=" + _deleteOfferRecord__return);


        }
        {
        System.out.println("Invoking crearSitioGuardarVideo...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarVideo _crearSitioGuardarVideo_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarVideoResponse _crearSitioGuardarVideo__return = port.crearSitioGuardarVideo(_crearSitioGuardarVideo_parameters);
        System.out.println("crearSitioGuardarVideo.result=" + _crearSitioGuardarVideo__return);


        }
        {
        System.out.println("Invoking insertUserDomain1...");
        com.infomovil.webapp.clientWsInfomovil.InsertUserDomain1 _insertUserDomain1_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertUserDomain1Response _insertUserDomain1__return = port.insertUserDomain1(_insertUserDomain1_parameters);
        System.out.println("insertUserDomain1.result=" + _insertUserDomain1__return);


        }
        {
        System.out.println("Invoking crearSitioUpdateImage...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioUpdateImage _crearSitioUpdateImage_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioUpdateImageResponse _crearSitioUpdateImage__return = port.crearSitioUpdateImage(_crearSitioUpdateImage_parameters);
        System.out.println("crearSitioUpdateImage.result=" + _crearSitioUpdateImage__return);


        }
        {
        System.out.println("Invoking sessionActiva...");
        com.infomovil.webapp.clientWsInfomovil.SessionActiva _sessionActiva_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.SessionActivaResponse _sessionActiva__return = port.sessionActiva(_sessionActiva_parameters);
        System.out.println("sessionActiva.result=" + _sessionActiva__return);


        }
        {
        System.out.println("Invoking insertKeywordDataAddress...");
        com.infomovil.webapp.clientWsInfomovil.InsertKeywordDataAddress _insertKeywordDataAddress_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertKeywordDataAddressResponse _insertKeywordDataAddress__return = port.insertKeywordDataAddress(_insertKeywordDataAddress_parameters);
        System.out.println("insertKeywordDataAddress.result=" + _insertKeywordDataAddress__return);


        }
        {
        System.out.println("Invoking deleteLocRecord...");
        com.infomovil.webapp.clientWsInfomovil.DeleteLocRecord _deleteLocRecord_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.DeleteLocRecordResponse _deleteLocRecord__return = port.deleteLocRecord(_deleteLocRecord_parameters);
        System.out.println("deleteLocRecord.result=" + _deleteLocRecord__return);


        }
        {
        System.out.println("Invoking insertVideo...");
        com.infomovil.webapp.clientWsInfomovil.InsertVideo _insertVideo_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertVideoResponse _insertVideo__return = port.insertVideo(_insertVideo_parameters);
        System.out.println("insertVideo.result=" + _insertVideo__return);


        }
        {
        System.out.println("Invoking getItemsGratisDomain...");
        com.infomovil.webapp.clientWsInfomovil.GetItemsGratisDomain _getItemsGratisDomain_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GetItemsGratisDomainResponse _getItemsGratisDomain__return = port.getItemsGratisDomain(_getItemsGratisDomain_parameters);
        System.out.println("getItemsGratisDomain.result=" + _getItemsGratisDomain__return);


        }
        {
        System.out.println("Invoking insertRecordNaptr...");
        com.infomovil.webapp.clientWsInfomovil.InsertRecordNaptr _insertRecordNaptr_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertRecordNaptrResponse _insertRecordNaptr__return = port.insertRecordNaptr(_insertRecordNaptr_parameters);
        System.out.println("insertRecordNaptr.result=" + _insertRecordNaptr__return);


        }
        {
        System.out.println("Invoking crearSitioGetWebHash...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGetWebHash _crearSitioGetWebHash_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGetWebHashResponse _crearSitioGetWebHash__return = port.crearSitioGetWebHash(_crearSitioGetWebHash_parameters);
        System.out.println("crearSitioGetWebHash.result=" + _crearSitioGetWebHash__return);


        }
        {
        System.out.println("Invoking insertImage...");
        com.infomovil.webapp.clientWsInfomovil.InsertImage _insertImage_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertImageResponse _insertImage__return = port.insertImage(_insertImage_parameters);
        System.out.println("insertImage.result=" + _insertImage__return);


        }
        {
        System.out.println("Invoking getDomain...");
        java.lang.String _getDomain_email = "";
        java.lang.String _getDomain_password = "";
        java.lang.String _getDomain_tipoDispositivo = "";
        java.lang.String _getDomain_sistema = "";
        java.lang.String _getDomain_notificacion = "";
        java.lang.String _getDomain_redSocial = "";
        java.lang.String _getDomain_suscrito = "";
        java.lang.String _getDomain_tipoPlan = "";
        java.lang.String _getDomain_medioPago = "";
        java.lang.String _getDomain_versionSistema = "";
        com.infomovil.webapp.clientWsInfomovil.DominioVO _getDomain__return = port.getDomain(_getDomain_email, _getDomain_password, _getDomain_tipoDispositivo, _getDomain_sistema, _getDomain_notificacion, _getDomain_redSocial, _getDomain_suscrito, _getDomain_tipoPlan, _getDomain_medioPago, _getDomain_versionSistema);
        System.out.println("getDomain.result=" + _getDomain__return);


        }
        {
        System.out.println("Invoking updateinsertOfferRecord...");
        com.infomovil.webapp.clientWsInfomovil.UpdateinsertOfferRecord _updateinsertOfferRecord_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateinsertOfferRecordResponse _updateinsertOfferRecord__return = port.updateinsertOfferRecord(_updateinsertOfferRecord_parameters);
        System.out.println("updateinsertOfferRecord.result=" + _updateinsertOfferRecord__return);


        }
        {
        System.out.println("Invoking crearSitioPublicar...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioPublicar _crearSitioPublicar_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioPublicarResponse _crearSitioPublicar__return = port.crearSitioPublicar(_crearSitioPublicar_parameters);
        System.out.println("crearSitioPublicar.result=" + _crearSitioPublicar__return);


        }
        {
        System.out.println("Invoking getExistUser...");
        com.infomovil.webapp.clientWsInfomovil.GetExistUser _getExistUser_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GetExistUserResponse _getExistUser__return = port.getExistUser(_getExistUser_parameters);
        System.out.println("getExistUser.result=" + _getExistUser__return);


        }
        {
        System.out.println("Invoking insertKeyWordData...");
        com.infomovil.webapp.clientWsInfomovil.InsertKeyWordData _insertKeyWordData_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertKeyWordDataResponse _insertKeyWordData__return = port.insertKeyWordData(_insertKeyWordData_parameters);
        System.out.println("insertKeyWordData.result=" + _insertKeyWordData__return);


        }
        {
        System.out.println("Invoking updateInserLocRecord...");
        com.infomovil.webapp.clientWsInfomovil.UpdateInserLocRecord _updateInserLocRecord_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateInserLocRecordResponse _updateInserLocRecord__return = port.updateInserLocRecord(_updateInserLocRecord_parameters);
        System.out.println("updateInserLocRecord.result=" + _updateInserLocRecord__return);


        }
        {
        System.out.println("Invoking generaHashMovilizaSitio...");
        com.infomovil.webapp.clientWsInfomovil.GeneraHashMovilizaSitio _generaHashMovilizaSitio_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GeneraHashMovilizaSitioResponse _generaHashMovilizaSitio__return = port.generaHashMovilizaSitio(_generaHashMovilizaSitio_parameters);
        System.out.println("generaHashMovilizaSitio.result=" + _generaHashMovilizaSitio__return);


        }
        {
        System.out.println("Invoking crearSitioGuardar...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardar _crearSitioGuardar_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarResponse _crearSitioGuardar__return = port.crearSitioGuardar(_crearSitioGuardar_parameters);
        System.out.println("crearSitioGuardar.result=" + _crearSitioGuardar__return);


        }
        {
        System.out.println("Invoking cambioPassword...");
        com.infomovil.webapp.clientWsInfomovil.CambioPassword _cambioPassword_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CambioPasswordResponse _cambioPassword__return = port.cambioPassword(_cambioPassword_parameters);
        System.out.println("cambioPassword.result=" + _cambioPassword__return);


        }
        {
        System.out.println("Invoking updateImage...");
        java.lang.String _updateImage_domainId = "";
        java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO> _updateImage_arg1 = null;
        java.lang.String _updateImage_token = "";
        java.lang.String _updateImage_sistema = "";
        java.lang.String _updateImage_versionSistema = "";
        com.infomovil.webapp.clientWsInfomovil.DominioVO _updateImage__return = port.updateImage(_updateImage_domainId, _updateImage_arg1, _updateImage_token, _updateImage_sistema, _updateImage_versionSistema);
        System.out.println("updateImage.result=" + _updateImage__return);


        }
        {
        System.out.println("Invoking updateRecordNaptr...");
        java.lang.String _updateRecordNaptr_domainId = "";
        java.util.List<com.infomovil.webapp.clientWsInfomovil.RecordNaptrVO> _updateRecordNaptr_recordNaptrVO = null;
        java.lang.String _updateRecordNaptr_token = "";
        com.infomovil.webapp.clientWsInfomovil.DominioVO _updateRecordNaptr__return = port.updateRecordNaptr(_updateRecordNaptr_domainId, _updateRecordNaptr_recordNaptrVO, _updateRecordNaptr_token);
        System.out.println("updateRecordNaptr.result=" + _updateRecordNaptr__return);


        }
        {
        System.out.println("Invoking getExistDomain...");
        com.infomovil.webapp.clientWsInfomovil.GetExistDomain _getExistDomain_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GetExistDomainResponse _getExistDomain__return = port.getExistDomain(_getExistDomain_parameters);
        System.out.println("getExistDomain.result=" + _getExistDomain__return);


        }
        {
        System.out.println("Invoking deleteImage...");
        com.infomovil.webapp.clientWsInfomovil.DeleteImage _deleteImage_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.DeleteImageResponse _deleteImage__return = port.deleteImage(_deleteImage_parameters);
        System.out.println("deleteImage.result=" + _deleteImage__return);


        }
        {
        System.out.println("Invoking crearSitioResetPassword...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioResetPassword _crearSitioResetPassword_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioResetPasswordResponse _crearSitioResetPassword__return = port.crearSitioResetPassword(_crearSitioResetPassword_parameters);
        System.out.println("crearSitioResetPassword.result=" + _crearSitioResetPassword__return);


        }
        {
        System.out.println("Invoking deleteRecordNaptr...");
        com.infomovil.webapp.clientWsInfomovil.DeleteRecordNaptr _deleteRecordNaptr_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.DeleteRecordNaptrResponse _deleteRecordNaptr__return = port.deleteRecordNaptr(_deleteRecordNaptr_parameters);
        System.out.println("deleteRecordNaptr.result=" + _deleteRecordNaptr__return);


        }
        {
        System.out.println("Invoking crearSitioRegistrar...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioRegistrar _crearSitioRegistrar_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioRegistrarResponse _crearSitioRegistrar__return = port.crearSitioRegistrar(_crearSitioRegistrar_parameters);
        System.out.println("crearSitioRegistrar.result=" + _crearSitioRegistrar__return);


        }
        {
        System.out.println("Invoking updateColor...");
        com.infomovil.webapp.clientWsInfomovil.UpdateColor _updateColor_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateColorResponse _updateColor__return = port.updateColor(_updateColor_parameters);
        System.out.println("updateColor.result=" + _updateColor__return);


        }
        {
        System.out.println("Invoking statusDominio...");
        com.infomovil.webapp.clientWsInfomovil.StatusDominio _statusDominio_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.StatusDominioResponse _statusDominio__return = port.statusDominio(_statusDominio_parameters);
        System.out.println("statusDominio.result=" + _statusDominio__return);


        }
        {
        System.out.println("Invoking crearSitioLogin...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioLogin _crearSitioLogin_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioLoginResponse _crearSitioLogin__return = port.crearSitioLogin(_crearSitioLogin_parameters);
        System.out.println("crearSitioLogin.result=" + _crearSitioLogin__return);


        }
        {
        System.out.println("Invoking deleteVideo...");
        com.infomovil.webapp.clientWsInfomovil.DeleteVideo _deleteVideo_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.DeleteVideoResponse _deleteVideo__return = port.deleteVideo(_deleteVideo_parameters);
        System.out.println("deleteVideo.result=" + _deleteVideo__return);


        }
        {
        System.out.println("Invoking compraDominio...");
        com.infomovil.webapp.clientWsInfomovil.CompraDominio _compraDominio_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CompraDominioResponse _compraDominio__return = port.compraDominio(_compraDominio_parameters);
        System.out.println("compraDominio.result=" + _compraDominio__return);


        }
        {
        System.out.println("Invoking crearSitioGuardarUbicacion...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarUbicacion _crearSitioGuardarUbicacion_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioGuardarUbicacionResponse _crearSitioGuardarUbicacion__return = port.crearSitioGuardarUbicacion(_crearSitioGuardarUbicacion_parameters);
        System.out.println("crearSitioGuardarUbicacion.result=" + _crearSitioGuardarUbicacion__return);


        }
        {
        System.out.println("Invoking getNumVisitas...");
        com.infomovil.webapp.clientWsInfomovil.GetNumVisitas _getNumVisitas_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GetNumVisitasResponse _getNumVisitas__return = port.getNumVisitas(_getNumVisitas_parameters);
        System.out.println("getNumVisitas.result=" + _getNumVisitas__return);


        }
        {
        System.out.println("Invoking insertUpdateInfoUser...");
        com.infomovil.webapp.clientWsInfomovil.InsertUpdateInfoUser _insertUpdateInfoUser_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertUpdateInfoUserResponse _insertUpdateInfoUser__return = port.insertUpdateInfoUser(_insertUpdateInfoUser_parameters);
        System.out.println("insertUpdateInfoUser.result=" + _insertUpdateInfoUser__return);


        }
        {
        System.out.println("Invoking deleteKeyWordData...");
        com.infomovil.webapp.clientWsInfomovil.DeleteKeyWordData _deleteKeyWordData_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.DeleteKeyWordDataResponse _deleteKeyWordData__return = port.deleteKeyWordData(_deleteKeyWordData_parameters);
        System.out.println("deleteKeyWordData.result=" + _deleteKeyWordData__return);


        }
        {
        System.out.println("Invoking updateKeyWordData...");
        com.infomovil.webapp.clientWsInfomovil.UpdateKeyWordData _updateKeyWordData_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateKeyWordDataResponse _updateKeyWordData__return = port.updateKeyWordData(_updateKeyWordData_parameters);
        System.out.println("updateKeyWordData.result=" + _updateKeyWordData__return);


        }
        {
        System.out.println("Invoking updateTemplate...");
        com.infomovil.webapp.clientWsInfomovil.UpdateTemplate _updateTemplate_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateTemplateResponse _updateTemplate__return = port.updateTemplate(_updateTemplate_parameters);
        System.out.println("updateTemplate.result=" + _updateTemplate__return);


        }
        {
        System.out.println("Invoking getEstadisticas...");
        com.infomovil.webapp.clientWsInfomovil.GetEstadisticas _getEstadisticas_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GetEstadisticasResponse _getEstadisticas__return = port.getEstadisticas(_getEstadisticas_parameters);
        System.out.println("getEstadisticas.result=" + _getEstadisticas__return);


        }
        {
        System.out.println("Invoking crearSitioDeleteImage...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioDeleteImage _crearSitioDeleteImage_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioDeleteImageResponse _crearSitioDeleteImage__return = port.crearSitioDeleteImage(_crearSitioDeleteImage_parameters);
        System.out.println("crearSitioDeleteImage.result=" + _crearSitioDeleteImage__return);


        }
        {
        System.out.println("Invoking cerrarSession...");
        com.infomovil.webapp.clientWsInfomovil.CerrarSession _cerrarSession_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CerrarSessionResponse _cerrarSession__return = port.cerrarSession(_cerrarSession_parameters);
        System.out.println("cerrarSession.result=" + _cerrarSession__return);


        }
        {
        System.out.println("Invoking crearImagenes...");
        int _crearImagenes__return = port.crearImagenes();
        System.out.println("crearImagenes.result=" + _crearImagenes__return);


        }
        {
        System.out.println("Invoking cancelarCuenta...");
        com.infomovil.webapp.clientWsInfomovil.CancelarCuenta _cancelarCuenta_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CancelarCuentaResponse _cancelarCuenta__return = port.cancelarCuenta(_cancelarCuenta_parameters);
        System.out.println("cancelarCuenta.result=" + _cancelarCuenta__return);


        }
        {
        System.out.println("Invoking updateTextRecord...");
        com.infomovil.webapp.clientWsInfomovil.UpdateTextRecord _updateTextRecord_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateTextRecordResponse _updateTextRecord__return = port.updateTextRecord(_updateTextRecord_parameters);
        System.out.println("updateTextRecord.result=" + _updateTextRecord__return);


        }
        {
        System.out.println("Invoking crearSitioInsertImage...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioInsertImage _crearSitioInsertImage_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioInsertImageResponse _crearSitioInsertImage__return = port.crearSitioInsertImage(_crearSitioInsertImage_parameters);
        System.out.println("crearSitioInsertImage.result=" + _crearSitioInsertImage__return);


        }
        {
        System.out.println("Invoking getExistCampaniaByMail...");
        com.infomovil.webapp.clientWsInfomovil.GetExistCampaniaByMail _getExistCampaniaByMail_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GetExistCampaniaByMailResponse _getExistCampaniaByMail__return = port.getExistCampaniaByMail(_getExistCampaniaByMail_parameters);
        System.out.println("getExistCampaniaByMail.result=" + _getExistCampaniaByMail__return);


        }
        {
        System.out.println("Invoking getDomainLogin...");
        java.lang.String _getDomainLogin_email = "";
        java.lang.String _getDomainLogin_password = "";
        java.lang.String _getDomainLogin_tipoDispositivo = "";
        java.lang.String _getDomainLogin_sistema = "";
        java.lang.String _getDomainLogin_notificacion = "";
        java.lang.String _getDomainLogin_redSocial = "";
        java.lang.String _getDomainLogin_suscrito = "";
        java.lang.String _getDomainLogin_tipoPlan = "";
        java.lang.String _getDomainLogin_medioPago = "";
        java.lang.String _getDomainLogin_versionSistema = "";
        com.infomovil.webapp.clientWsInfomovil.DominioVO _getDomainLogin__return = port.getDomainLogin(_getDomainLogin_email, _getDomainLogin_password, _getDomainLogin_tipoDispositivo, _getDomainLogin_sistema, _getDomainLogin_notificacion, _getDomainLogin_redSocial, _getDomainLogin_suscrito, _getDomainLogin_tipoPlan, _getDomainLogin_medioPago, _getDomainLogin_versionSistema);
        System.out.println("getDomainLogin.result=" + _getDomainLogin__return);


        }
        {
        System.out.println("Invoking getImagenes...");
        java.lang.String _getImagenes_email = "";
        java.lang.Integer _getImagenes_domainId = null;
        java.lang.String _getImagenes_sistema = "";
        java.lang.String _getImagenes_versionSistema = "";
        java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO> _getImagenes__return = port.getImagenes(_getImagenes_email, _getImagenes_domainId, _getImagenes_sistema, _getImagenes_versionSistema);
        System.out.println("getImagenes.result=" + _getImagenes__return);


        }
        {
        System.out.println("Invoking cambiaNombreRecurso...");
        com.infomovil.webapp.clientWsInfomovil.CambiaNombreRecurso _cambiaNombreRecurso_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CambiaNombreRecursoResponse _cambiaNombreRecurso__return = port.cambiaNombreRecurso(_cambiaNombreRecurso_parameters);
        System.out.println("cambiaNombreRecurso.result=" + _cambiaNombreRecurso__return);


        }
        {
        System.out.println("Invoking crearSitioExisteDominio...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioExisteDominio _crearSitioExisteDominio_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioExisteDominioResponse _crearSitioExisteDominio__return = port.crearSitioExisteDominio(_crearSitioExisteDominio_parameters);
        System.out.println("crearSitioExisteDominio.result=" + _crearSitioExisteDominio__return);


        }
        {
        System.out.println("Invoking insertUserCam...");
        com.infomovil.webapp.clientWsInfomovil.InsertUserCam _insertUserCam_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.InsertUserCamResponse _insertUserCam__return = port.insertUserCam(_insertUserCam_parameters);
        System.out.println("insertUserCam.result=" + _insertUserCam__return);


        }
        {
        System.out.println("Invoking updateDesCorta...");
        com.infomovil.webapp.clientWsInfomovil.UpdateDesCorta _updateDesCorta_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.UpdateDesCortaResponse _updateDesCorta__return = port.updateDesCorta(_updateDesCorta_parameters);
        System.out.println("updateDesCorta.result=" + _updateDesCorta__return);


        }
        {
        System.out.println("Invoking catalogoDominios...");
        java.util.List<com.infomovil.webapp.clientWsInfomovil.Catalogo> _catalogoDominios__return = port.catalogoDominios();
        System.out.println("catalogoDominios.result=" + _catalogoDominios__return);


        }
        {
        System.out.println("Invoking createDomain...");
        com.infomovil.webapp.clientWsInfomovil.CreateDomain _createDomain_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CreateDomainResponse _createDomain__return = port.createDomain(_createDomain_parameters);
        System.out.println("createDomain.result=" + _createDomain__return);


        }
        {
        System.out.println("Invoking getFechaExpiracion...");
        com.infomovil.webapp.clientWsInfomovil.GetFechaExpiracion _getFechaExpiracion_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GetFechaExpiracionResponse _getFechaExpiracion__return = port.getFechaExpiracion(_getFechaExpiracion_parameters);
        System.out.println("getFechaExpiracion.result=" + _getFechaExpiracion__return);


        }
        {
        System.out.println("Invoking generaHashCambioPassword...");
        com.infomovil.webapp.clientWsInfomovil.GeneraHashCambioPassword _generaHashCambioPassword_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.GeneraHashCambioPasswordResponse _generaHashCambioPassword__return = port.generaHashCambioPassword(_generaHashCambioPassword_parameters);
        System.out.println("generaHashCambioPassword.result=" + _generaHashCambioPassword__return);


        }
        {
        System.out.println("Invoking crearSitioCargar...");
        com.infomovil.webapp.clientWsInfomovil.CrearSitioCargar _crearSitioCargar_parameters = null;
        com.infomovil.webapp.clientWsInfomovil.CrearSitioCargarResponse _crearSitioCargar__return = port.crearSitioCargar(_crearSitioCargar_parameters);
        System.out.println("crearSitioCargar.result=" + _crearSitioCargar__return);


        }

        System.exit(0);
    }

}
