package com.infomovil.webapp.clientWsInfomovil;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-09-22T12:26:22.631-05:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://ws.webservice.infomovil.org/", name = "WsInfomovilDomain")
@XmlSeeAlso({ObjectFactory.class})
public interface WsInfomovilDomain {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateDomainResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateDomainRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateDomainResponse")
    @WebMethod
    public UpdateDomainResponse updateDomain(
        @WebParam(partName = "parameters", name = "updateDomain", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateDomain parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteOfferRecordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteOfferRecordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteOfferRecordResponse")
    @WebMethod
    public DeleteOfferRecordResponse deleteOfferRecord(
        @WebParam(partName = "parameters", name = "deleteOfferRecord", targetNamespace = "http://ws.webservice.infomovil.org/")
        DeleteOfferRecord parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_guardarVideoResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_guardarVideoRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_guardarVideoResponse")
    @WebMethod(operationName = "crearSitio_guardarVideo")
    public CrearSitioGuardarVideoResponse crearSitioGuardarVideo(
        @WebParam(partName = "parameters", name = "crearSitio_guardarVideo", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioGuardarVideo parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_getProductosUsuarioResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_getProductosUsuarioRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_getProductosUsuarioResponse")
    @WebMethod(operationName = "crearSitio_getProductosUsuario")
    public CrearSitioGetProductosUsuarioResponse crearSitioGetProductosUsuario(
        @WebParam(partName = "parameters", name = "crearSitio_getProductosUsuario", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioGetProductosUsuario parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertUserDomain1Response", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertUserDomain1Request", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertUserDomain1Response")
    @WebMethod
    public InsertUserDomain1Response insertUserDomain1(
        @WebParam(partName = "parameters", name = "insertUserDomain1", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertUserDomain1 parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_updateImageResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_updateImageRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_updateImageResponse")
    @WebMethod(operationName = "crearSitio_updateImage")
    public CrearSitioUpdateImageResponse crearSitioUpdateImage(
        @WebParam(partName = "parameters", name = "crearSitio_updateImage", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioUpdateImage parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "sessionActivaResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/sessionActivaRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/sessionActivaResponse")
    @WebMethod
    public SessionActivaResponse sessionActiva(
        @WebParam(partName = "parameters", name = "sessionActiva", targetNamespace = "http://ws.webservice.infomovil.org/")
        SessionActiva parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertKeywordDataAddressResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertKeywordDataAddressRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertKeywordDataAddressResponse")
    @WebMethod
    public InsertKeywordDataAddressResponse insertKeywordDataAddress(
        @WebParam(partName = "parameters", name = "insertKeywordDataAddress", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertKeywordDataAddress parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteLocRecordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteLocRecordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteLocRecordResponse")
    @WebMethod
    public DeleteLocRecordResponse deleteLocRecord(
        @WebParam(partName = "parameters", name = "deleteLocRecord", targetNamespace = "http://ws.webservice.infomovil.org/")
        DeleteLocRecord parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertVideoResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertVideoRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertVideoResponse")
    @WebMethod
    public InsertVideoResponse insertVideo(
        @WebParam(partName = "parameters", name = "insertVideo", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertVideo parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getItemsGratisDomainResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getItemsGratisDomainRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getItemsGratisDomainResponse")
    @WebMethod
    public GetItemsGratisDomainResponse getItemsGratisDomain(
        @WebParam(partName = "parameters", name = "getItemsGratisDomain", targetNamespace = "http://ws.webservice.infomovil.org/")
        GetItemsGratisDomain parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_getWebHashResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_getWebHashRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_getWebHashResponse")
    @WebMethod(operationName = "crearSitio_getWebHash")
    public CrearSitioGetWebHashResponse crearSitioGetWebHash(
        @WebParam(partName = "parameters", name = "crearSitio_getWebHash", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioGetWebHash parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertRecordNaptrResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertRecordNaptrRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertRecordNaptrResponse")
    @WebMethod
    public InsertRecordNaptrResponse insertRecordNaptr(
        @WebParam(partName = "parameters", name = "insertRecordNaptr", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertRecordNaptr parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertImageResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertImageRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertImageResponse")
    @WebMethod
    public InsertImageResponse insertImage(
        @WebParam(partName = "parameters", name = "insertImage", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertImage parameters
    );

    @WebResult(name = "Domain", targetNamespace = "")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getDomainRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getDomainResponse")
    @RequestWrapper(localName = "getDomain", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.GetDomain")
    @WebMethod
    @ResponseWrapper(localName = "getDomainResponse", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.GetDomainResponse")
    public com.infomovil.webapp.clientWsInfomovil.DominioVO getDomain(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "tipoDispositivo", targetNamespace = "")
        java.lang.String tipoDispositivo,
        @WebParam(name = "sistema", targetNamespace = "")
        java.lang.String sistema,
        @WebParam(name = "notificacion", targetNamespace = "")
        java.lang.String notificacion,
        @WebParam(name = "redSocial", targetNamespace = "")
        java.lang.String redSocial,
        @WebParam(name = "suscrito", targetNamespace = "")
        java.lang.String suscrito,
        @WebParam(name = "tipoPlan", targetNamespace = "")
        java.lang.String tipoPlan,
        @WebParam(name = "medioPago", targetNamespace = "")
        java.lang.String medioPago,
        @WebParam(name = "versionSistema", targetNamespace = "")
        java.lang.String versionSistema
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_publicarResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_publicarRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_publicarResponse")
    @WebMethod(operationName = "crearSitio_publicar")
    public CrearSitioPublicarResponse crearSitioPublicar(
        @WebParam(partName = "parameters", name = "crearSitio_publicar", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioPublicar parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateinsertOfferRecordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateinsertOfferRecordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateinsertOfferRecordResponse")
    @WebMethod
    public UpdateinsertOfferRecordResponse updateinsertOfferRecord(
        @WebParam(partName = "parameters", name = "updateinsertOfferRecord", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateinsertOfferRecord parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getExistUserResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getExistUserRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getExistUserResponse")
    @WebMethod
    public GetExistUserResponse getExistUser(
        @WebParam(partName = "parameters", name = "getExistUser", targetNamespace = "http://ws.webservice.infomovil.org/")
        GetExistUser parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertKeyWordDataResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertKeyWordDataRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertKeyWordDataResponse")
    @WebMethod
    public InsertKeyWordDataResponse insertKeyWordData(
        @WebParam(partName = "parameters", name = "insertKeyWordData", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertKeyWordData parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateInserLocRecordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateInserLocRecordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateInserLocRecordResponse")
    @WebMethod
    public UpdateInserLocRecordResponse updateInserLocRecord(
        @WebParam(partName = "parameters", name = "updateInserLocRecord", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateInserLocRecord parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "generaHashMovilizaSitioResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/generaHashMovilizaSitioRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/generaHashMovilizaSitioResponse")
    @WebMethod
    public GeneraHashMovilizaSitioResponse generaHashMovilizaSitio(
        @WebParam(partName = "parameters", name = "generaHashMovilizaSitio", targetNamespace = "http://ws.webservice.infomovil.org/")
        GeneraHashMovilizaSitio parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_guardarResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_guardarRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_guardarResponse")
    @WebMethod(operationName = "crearSitio_guardar")
    public CrearSitioGuardarResponse crearSitioGuardar(
        @WebParam(partName = "parameters", name = "crearSitio_guardar", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioGuardar parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cambioPasswordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cambioPasswordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cambioPasswordResponse")
    @WebMethod
    public CambioPasswordResponse cambioPassword(
        @WebParam(partName = "parameters", name = "cambioPassword", targetNamespace = "http://ws.webservice.infomovil.org/")
        CambioPassword parameters
    );

    @WebResult(name = "RespuestaVO", targetNamespace = "")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateRecordNaptrRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateRecordNaptrResponse")
    @RequestWrapper(localName = "updateRecordNaptr", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.UpdateRecordNaptr")
    @WebMethod
    @ResponseWrapper(localName = "updateRecordNaptrResponse", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.UpdateRecordNaptrResponse")
    public com.infomovil.webapp.clientWsInfomovil.DominioVO updateRecordNaptr(
        @WebParam(name = "domain_id", targetNamespace = "")
        java.lang.String domainId,
        @WebParam(name = "RecordNaptrVO", targetNamespace = "")
        java.util.List<com.infomovil.webapp.clientWsInfomovil.RecordNaptrVO> recordNaptrVO,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebResult(name = "ImagenVO", targetNamespace = "")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateImageRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateImageResponse")
    @RequestWrapper(localName = "updateImage", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.UpdateImage")
    @WebMethod
    @ResponseWrapper(localName = "updateImageResponse", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.UpdateImageResponse")
    public com.infomovil.webapp.clientWsInfomovil.DominioVO updateImage(
        @WebParam(name = "domainId", targetNamespace = "")
        java.lang.String domainId,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO> arg1,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "sistema", targetNamespace = "")
        java.lang.String sistema,
        @WebParam(name = "versionSistema", targetNamespace = "")
        java.lang.String versionSistema
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getExistDomainResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getExistDomainRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getExistDomainResponse")
    @WebMethod
    public GetExistDomainResponse getExistDomain(
        @WebParam(partName = "parameters", name = "getExistDomain", targetNamespace = "http://ws.webservice.infomovil.org/")
        GetExistDomain parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteImageResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteImageRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteImageResponse")
    @WebMethod
    public DeleteImageResponse deleteImage(
        @WebParam(partName = "parameters", name = "deleteImage", targetNamespace = "http://ws.webservice.infomovil.org/")
        DeleteImage parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_resetPasswordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_resetPasswordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_resetPasswordResponse")
    @WebMethod(operationName = "crearSitio_resetPassword")
    public CrearSitioResetPasswordResponse crearSitioResetPassword(
        @WebParam(partName = "parameters", name = "crearSitio_resetPassword", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioResetPassword parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_registrarResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_registrarRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_registrarResponse")
    @WebMethod(operationName = "crearSitio_registrar")
    public CrearSitioRegistrarResponse crearSitioRegistrar(
        @WebParam(partName = "parameters", name = "crearSitio_registrar", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioRegistrar parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteRecordNaptrResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteRecordNaptrRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteRecordNaptrResponse")
    @WebMethod
    public DeleteRecordNaptrResponse deleteRecordNaptr(
        @WebParam(partName = "parameters", name = "deleteRecordNaptr", targetNamespace = "http://ws.webservice.infomovil.org/")
        DeleteRecordNaptr parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "statusDominioResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/statusDominioRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/statusDominioResponse")
    @WebMethod
    public StatusDominioResponse statusDominio(
        @WebParam(partName = "parameters", name = "statusDominio", targetNamespace = "http://ws.webservice.infomovil.org/")
        StatusDominio parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_loginResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_loginRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_loginResponse")
    @WebMethod(operationName = "crearSitio_login")
    public CrearSitioLoginResponse crearSitioLogin(
        @WebParam(partName = "parameters", name = "crearSitio_login", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioLogin parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateColorResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateColorRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateColorResponse")
    @WebMethod
    public UpdateColorResponse updateColor(
        @WebParam(partName = "parameters", name = "updateColor", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateColor parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteVideoResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteVideoRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteVideoResponse")
    @WebMethod
    public DeleteVideoResponse deleteVideo(
        @WebParam(partName = "parameters", name = "deleteVideo", targetNamespace = "http://ws.webservice.infomovil.org/")
        DeleteVideo parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_guardarUbicacionResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_guardarUbicacionRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_guardarUbicacionResponse")
    @WebMethod(operationName = "crearSitio_guardarUbicacion")
    public CrearSitioGuardarUbicacionResponse crearSitioGuardarUbicacion(
        @WebParam(partName = "parameters", name = "crearSitio_guardarUbicacion", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioGuardarUbicacion parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "compraDominioResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/compraDominioRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/compraDominioResponse")
    @WebMethod
    public CompraDominioResponse compraDominio(
        @WebParam(partName = "parameters", name = "compraDominio", targetNamespace = "http://ws.webservice.infomovil.org/")
        CompraDominio parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getNumVisitasResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getNumVisitasRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getNumVisitasResponse")
    @WebMethod
    public GetNumVisitasResponse getNumVisitas(
        @WebParam(partName = "parameters", name = "getNumVisitas", targetNamespace = "http://ws.webservice.infomovil.org/")
        GetNumVisitas parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertUpdateInfoUserResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertUpdateInfoUserRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertUpdateInfoUserResponse")
    @WebMethod
    public InsertUpdateInfoUserResponse insertUpdateInfoUser(
        @WebParam(partName = "parameters", name = "insertUpdateInfoUser", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertUpdateInfoUser parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deleteKeyWordDataResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteKeyWordDataRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/deleteKeyWordDataResponse")
    @WebMethod
    public DeleteKeyWordDataResponse deleteKeyWordData(
        @WebParam(partName = "parameters", name = "deleteKeyWordData", targetNamespace = "http://ws.webservice.infomovil.org/")
        DeleteKeyWordData parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateKeyWordDataResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateKeyWordDataRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateKeyWordDataResponse")
    @WebMethod
    public UpdateKeyWordDataResponse updateKeyWordData(
        @WebParam(partName = "parameters", name = "updateKeyWordData", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateKeyWordData parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEstadisticasResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getEstadisticasRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getEstadisticasResponse")
    @WebMethod
    public GetEstadisticasResponse getEstadisticas(
        @WebParam(partName = "parameters", name = "getEstadisticas", targetNamespace = "http://ws.webservice.infomovil.org/")
        GetEstadisticas parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateTemplateResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateTemplateRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateTemplateResponse")
    @WebMethod
    public UpdateTemplateResponse updateTemplate(
        @WebParam(partName = "parameters", name = "updateTemplate", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateTemplate parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_deleteImageResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_deleteImageRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_deleteImageResponse")
    @WebMethod(operationName = "crearSitio_deleteImage")
    public CrearSitioDeleteImageResponse crearSitioDeleteImage(
        @WebParam(partName = "parameters", name = "crearSitio_deleteImage", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioDeleteImage parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cerrarSessionResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cerrarSessionRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cerrarSessionResponse")
    @WebMethod
    public CerrarSessionResponse cerrarSession(
        @WebParam(partName = "parameters", name = "cerrarSession", targetNamespace = "http://ws.webservice.infomovil.org/")
        CerrarSession parameters
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearImagenesRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearImagenesResponse")
    @RequestWrapper(localName = "crearImagenes", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.CrearImagenes")
    @WebMethod
    @ResponseWrapper(localName = "crearImagenesResponse", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.CrearImagenesResponse")
    public int crearImagenes();

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_intentoPagoResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_intentoPagoRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_intentoPagoResponse")
    @WebMethod(operationName = "crearSitio_intentoPago")
    public CrearSitioIntentoPagoResponse crearSitioIntentoPago(
        @WebParam(partName = "parameters", name = "crearSitio_intentoPago", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioIntentoPago parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cancelarCuentaResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cancelarCuentaRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cancelarCuentaResponse")
    @WebMethod
    public CancelarCuentaResponse cancelarCuenta(
        @WebParam(partName = "parameters", name = "cancelarCuenta", targetNamespace = "http://ws.webservice.infomovil.org/")
        CancelarCuenta parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateTextRecordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateTextRecordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateTextRecordResponse")
    @WebMethod
    public UpdateTextRecordResponse updateTextRecord(
        @WebParam(partName = "parameters", name = "updateTextRecord", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateTextRecord parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_insertImageResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_insertImageRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_insertImageResponse")
    @WebMethod(operationName = "crearSitio_insertImage")
    public CrearSitioInsertImageResponse crearSitioInsertImage(
        @WebParam(partName = "parameters", name = "crearSitio_insertImage", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioInsertImage parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getExistCampaniaByMailResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getExistCampaniaByMailRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getExistCampaniaByMailResponse")
    @WebMethod
    public GetExistCampaniaByMailResponse getExistCampaniaByMail(
        @WebParam(partName = "parameters", name = "getExistCampaniaByMail", targetNamespace = "http://ws.webservice.infomovil.org/")
        GetExistCampaniaByMail parameters
    );

    @WebResult(name = "Domain", targetNamespace = "")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getDomainLoginRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getDomainLoginResponse")
    @RequestWrapper(localName = "getDomainLogin", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.GetDomainLogin")
    @WebMethod
    @ResponseWrapper(localName = "getDomainLoginResponse", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.GetDomainLoginResponse")
    public com.infomovil.webapp.clientWsInfomovil.DominioVO getDomainLogin(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "tipoDispositivo", targetNamespace = "")
        java.lang.String tipoDispositivo,
        @WebParam(name = "sistema", targetNamespace = "")
        java.lang.String sistema,
        @WebParam(name = "notificacion", targetNamespace = "")
        java.lang.String notificacion,
        @WebParam(name = "redSocial", targetNamespace = "")
        java.lang.String redSocial,
        @WebParam(name = "suscrito", targetNamespace = "")
        java.lang.String suscrito,
        @WebParam(name = "tipoPlan", targetNamespace = "")
        java.lang.String tipoPlan,
        @WebParam(name = "medioPago", targetNamespace = "")
        java.lang.String medioPago,
        @WebParam(name = "versionSistema", targetNamespace = "")
        java.lang.String versionSistema
    );

    @WebResult(name = "ImagenesVO", targetNamespace = "")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getImagenesRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getImagenesResponse")
    @RequestWrapper(localName = "getImagenes", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.GetImagenes")
    @WebMethod
    @ResponseWrapper(localName = "getImagenesResponse", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.GetImagenesResponse")
    public java.util.List<com.infomovil.webapp.clientWsInfomovil.ImagenVO> getImagenes(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "domainId", targetNamespace = "")
        java.lang.Integer domainId,
        @WebParam(name = "sistema", targetNamespace = "")
        java.lang.String sistema,
        @WebParam(name = "versionSistema", targetNamespace = "")
        java.lang.String versionSistema
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "cambiaNombreRecursoResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cambiaNombreRecursoRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/cambiaNombreRecursoResponse")
    @WebMethod
    public CambiaNombreRecursoResponse cambiaNombreRecurso(
        @WebParam(partName = "parameters", name = "cambiaNombreRecurso", targetNamespace = "http://ws.webservice.infomovil.org/")
        CambiaNombreRecurso parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_existeDominioResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_existeDominioRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_existeDominioResponse")
    @WebMethod(operationName = "crearSitio_existeDominio")
    public CrearSitioExisteDominioResponse crearSitioExisteDominio(
        @WebParam(partName = "parameters", name = "crearSitio_existeDominio", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioExisteDominio parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "insertUserCamResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertUserCamRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/insertUserCamResponse")
    @WebMethod
    public InsertUserCamResponse insertUserCam(
        @WebParam(partName = "parameters", name = "insertUserCam", targetNamespace = "http://ws.webservice.infomovil.org/")
        InsertUserCam parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "updateDesCortaResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateDesCortaRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/updateDesCortaResponse")
    @WebMethod
    public UpdateDesCortaResponse updateDesCorta(
        @WebParam(partName = "parameters", name = "updateDesCorta", targetNamespace = "http://ws.webservice.infomovil.org/")
        UpdateDesCorta parameters
    );

    @WebResult(name = "CatalogoDominios", targetNamespace = "")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/catalogoDominiosRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/catalogoDominiosResponse")
    @RequestWrapper(localName = "catalogoDominios", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.CatalogoDominios")
    @WebMethod
    @ResponseWrapper(localName = "catalogoDominiosResponse", targetNamespace = "http://ws.webservice.infomovil.org/", className = "com.infomovil.webapp.clientWsInfomovil.CatalogoDominiosResponse")
    public java.util.List<com.infomovil.webapp.clientWsInfomovil.Catalogo> catalogoDominios();

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "createDomainResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/createDomainRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/createDomainResponse")
    @WebMethod
    public CreateDomainResponse createDomain(
        @WebParam(partName = "parameters", name = "createDomain", targetNamespace = "http://ws.webservice.infomovil.org/")
        CreateDomain parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getFechaExpiracionResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getFechaExpiracionRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/getFechaExpiracionResponse")
    @WebMethod
    public GetFechaExpiracionResponse getFechaExpiracion(
        @WebParam(partName = "parameters", name = "getFechaExpiracion", targetNamespace = "http://ws.webservice.infomovil.org/")
        GetFechaExpiracion parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "generaHashCambioPasswordResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/generaHashCambioPasswordRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/generaHashCambioPasswordResponse")
    @WebMethod
    public GeneraHashCambioPasswordResponse generaHashCambioPassword(
        @WebParam(partName = "parameters", name = "generaHashCambioPassword", targetNamespace = "http://ws.webservice.infomovil.org/")
        GeneraHashCambioPassword parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "crearSitio_cargarResponse", targetNamespace = "http://ws.webservice.infomovil.org/", partName = "parameters")
    @Action(input = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_cargarRequest", output = "http://ws.webservice.infomovil.org/WsInfomovilDomain/crearSitio_cargarResponse")
    @WebMethod(operationName = "crearSitio_cargar")
    public CrearSitioCargarResponse crearSitioCargar(
        @WebParam(partName = "parameters", name = "crearSitio_cargar", targetNamespace = "http://ws.webservice.infomovil.org/")
        CrearSitioCargar parameters
    );
}
